//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string TradeVolume { get; set; }
        public string TradeValue { get; set; }
        public string OpeningPrice { get; set; }
        public string HighestPrice { get; set; }
        public string LowestPrice { get; set; }
        public string ClosingPrice { get; set; }
        public string Change { get; set; }
        public string TransactionValue { get; set; }
        public string Date { get; set; }
        public string UpdateTime { get; set; }
        public string Gain { get; set; }
        public string Shock { get; set; }
        public string ForeignInvestment { get; set; }
        public string Investment { get; set; }
        public string Dealer { get; set; }
    }
}
