//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StockWarehouseEntities : DbContext
    {
        public StockWarehouseEntities()
            : base("name=StockWarehouseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<StockGroup> StockGroup { get; set; }
        public virtual DbSet<StockIndex> StockIndex { get; set; }
        public virtual DbSet<StockInventory> StockInventory { get; set; }
        public virtual DbSet<StockLineNotify> StockLineNotify { get; set; }
        public virtual DbSet<StockFutureCode> StockFutureCode { get; set; }
    }
}
