//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockIndex
    {
        public int Id { get; set; }
        public string DayOfWeek { get; set; }
        public string Date { get; set; }
        public string DJI { get; set; }
        public string DJI_QuoteChange { get; set; }
        public string NASDAQ { get; set; }
        public string NASDAQ_QuoteChange { get; set; }
        public string PHLX { get; set; }
        public string PHLX_QuoteChange { get; set; }
        public string MTX { get; set; }
        public string MTX_QuoteChange { get; set; }
        public string MTX_Open { get; set; }
        public string MTX_High { get; set; }
        public string TX { get; set; }
        public string TX_QuoteChange { get; set; }
        public string TX_Open { get; set; }
        public string TX_High { get; set; }
        public string TAIEX { get; set; }
        public string TAIEX_Open { get; set; }
        public string TAIEX_High { get; set; }
        public string ContinueName { get; set; }
        public string Remark { get; set; }
        public string Trend { get; set; }
        public string DJI_QuotePercent { get; set; }
        public string NASDAQ_QuotePercent { get; set; }
        public string PHLX_QuotePercent { get; set; }
        public string MTX_QuotePercent { get; set; }
        public string TX_QuotePercent { get; set; }
        public string TAIEX_QuoteChange { get; set; }
        public string TAIEX_QuotePercent { get; set; }
        public string Financing { get; set; }
        public string Volume { get; set; }
        public string TPEx { get; set; }
        public string TPEx_QuoteChange { get; set; }
        public string TPEx_QuotePercent { get; set; }
        public string MTX_Volume { get; set; }
        public string TX_Volume { get; set; }
        public string JuridicaPerson { get; set; }
    }
}
